config/routes.rb
Rails.application.routes.draw do
  root "products#home"
  get "/home", to: "products#home"
  get "/introduce", to: "static_pages#introduce"
  get "/register", to: "accounts#new"
  post "/register", to: "accounts#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/show/:id", to: "products#show"
  resources :accounts, except: %i( index destroy )
  resources :oders, only: [:new, :create]
  resources :products
  resources :carts, only: [:index, :create, :destroy] do
    collection do
      get "/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
      get "remove/:id", to: "carts#remove_from_cart", as: "remove_from"
      put "update_cart/:id", to: "carts#update_cart", as: "update"
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :find_product,
                :get_line_item,
                :check_residual_quantity?,
                only: [:create, :destroy, :update]
  before_action :logged_in?, only: [:index, :create]

  def index
    @cart_items = get_line_items_in_cart
    @cart_items.reverse!
  end

  def create
    if @item
      @item["quantity"] += params[:quantity].to_i
      flash[:info] = t "cart.cart_add"
    else
      current_cart << {product_id: @product.id, quantity: params[:quantity].to_i}
      flash[:success] = t "cart.cart_success"
    end
    session[:cart] = current_cart
    redirect_to root_path
  end

  def destroy
    if @item
      flash[:success] = t "cart.remove_cart_success"
      current_cart.delete(@item)
    else
      flash[:danger] = t "cart.remove_cart_fail"
    end
    redirect_to carts_path
  end

  def update
    if @item
      @item["quantity"] = params[:quantity].to_i
      flash.now[:success] = t "cart.update_cart_success"
    else
      flash[:danger] = t "cart.update_cart_fail"
    end
    redirect_to carts_path
  end

  private

  def check_residual_quantity?
    quantity = if @item
                 @item["quantity"] + params[:quantity].to_i
               else
                 params[:quantity].to_i
               end
    return if @product.check_residual_quantity? quantity

    flash[:danger] = t "cart.not_enough_product"
    redirect_to root_path
  end

  def get_line_item
    @item = find_product_in_cart @product
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    session[:cart] ||= Array.new
  end

  def find_product_in_cart product
    current_cart.find{|item| item["product_id"] == product.id}
  end

  def get_line_items_in_cart
    cart_items = []
    current_cart.each do |item|
      product = Product.find_by(id: item["product_id"])
      if product
        cart_items << {product: product, quantity: item["quantity"]}
      else
        current_cart.delete(item)
      end
    end
    cart_items
  end

  def line_total_price item
    item[:product].price * item[:quantity]
  end

  def total_of_money
    items = get_line_items_in_cart
    items.reduce(0){|a, e| a + e[:product].price * e[:quantity]}
  end
end

app/views/carts/index.html.erb
<% provide(:title, t("cart.cart")) %>
<div class="cart row-user">
  <div class="container cart_height">
    <table id="cart" class="table table-hover table-condensed">
      <thead>
        <tr>
          <th class="cart-name"><%= t "cart.product_name" %></th>
          <th class="cart-price%"><%= t "cart.price" %></th>
          <th class="cart-quantity"><%= t "cart.quantity" %></th>
          <th class="cart-total-money text-center"><%= t "cart.total_money"  %></th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.reverse! %>
        <% @cart_items.each do |item| %>
          <tr>
            <td>
              <div class="row">
                <div class="col-sm-2 hidden-xs">
                    <%= image_tag item[:product].image, class:"img-responsive width-edit" %>
                </div>
                <div class="col-sm-10">
                  <h4><%= item[:product].name %></h4>
                </div>
              </div>  
            </td>
            <td><%= number_to_currency item[:product].price %></td>
            <%= form_with(url: update_carts_path(item[:product]), local: false, method: :put) do |f| %>
              <td class="quantity">
                <%= f.number_field :quantity, value: item[:quantity], min: 1, class: "form-control text-center change-quatity" %>
                <%= f.hidden_field :id, value: item.dig(:product)&.id, class:"cart_product_id" %>
              </td>
            <% end %>
            <td data-th="subtotal" class="text-center"><%= number_to_currency line_total_price(item) %></td>
            <td>
              <%= link_to  remove_from_carts_path(item[:product]), class: "btn btn-primary bi bi-trash" do %>
                <%= t ("cart.remove") %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td>
            <%= link_to t("cart.continue_buy"),home_path, class:"btn btn-info bi bi-bag", type:"button" %>
            
          </td>
          <td colspan="2" class="hidden-xs"> </td>
          <td class="hidden-xs text-center">
            <strong>
          
              <%= t "cart.total_of_money" %> <%= number_to_currency total_of_money %>
            
            </strong>
          </td>
          <td >
            <%= link_to t("cart.pay"), new_oder_path, class: "btn btn-success bi bi-wallet2 " %>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
<%= javascript_include_tag "ajax_cart" %>