config/routes.rb
Rails.application.routes.draw do
  root "products#home"
  get "/home", to: "products#home"
  get "/introduce", to: "static_pages#introduce"
  get "/register", to: "accounts#new"
  post "/register", to: "accounts#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/show/:id", to: "products#show"
  resources :accounts, except: %i( index destroy )
  resources :oders, only: [:new, :create]
  resources :products
  resources :carts, only: [:index, :create, :destroy] do
    collection do
      get "/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
      get "remove/:id", to: "carts#remove_from_cart", as: "remove_from"
      put "update_cart/:id", to: "carts#update_cart", as: "update"
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :oder_details, dependent: :destroy
  belongs_to :category
  validates :image, presence: true, length: {minimum: Settings.length.image}
  scope :recent, ->{order updated_at: :DESC}
  scope :list_product, ->(id){where id: id}
  delegate :name, to: :category, prefix: true

  def check_residual_quantity? quantity_params
    quantity_params.positive? && residual >= quantity_params
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t "message.product_not_exits"
    redirect_to root_path
  end

  def home
    @products = Product.page(params[:page]).per(Settings.page_record_medium)
                       .recent
    @categorys = Category.pluck :name, :id
  end
end

app/views/products/_home_product.html.erb
<% @products.each do |product| %>
  <div class="col-lg-4 col-md-6">
    <div class="single-product">
      <div class="product-img">
        <%= image_tag product.image, class: "card-img" %>
      </div>
      <div class=" text-center">
        <%= link_to product.name, product, class: "text-dark link" %>
        <div class="mt-1 mb-1">
          <%= number_to_currency(product.price) %>
        </div>
        <%= link_to t(".buy"), product , class: "btn btn-danger mx-2 mb-2", type: "button" %>
      </div>
    </div>
  </div>
<% end %>
<nav aria-label="Page navigation example mt-1 paginate">
  <ul class="pagination justify-content-center">
    <h5><%= paginate @products %></h5>
  </ul>
</nav>

app/views/products/home.html.erb
<% provide :title, t("layouts.header.home") %>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="assets/banner1" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="assets/banner2" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="row mt-2">
  <div class= "col-6">
    <div class="row">
      <div class="col-5">
        <input class="form-control" name="min" value="" placeholder="Min Price">
      </div>
      <div class="col-5">
        <input class="form-control" name="max" value="" placeholder="Max Price">
      </div>
      <div class="col-2">
        <%= link_to t("layouts.header.search"), home_path, class: "btn btn-secondary", type: "button" %>
      </div>
    </div>
  </div>
  <div class="col-1">
  </div>
  <div class="col-5">
    <div class="row">
      <div class="col-2 mt-2">
        <%= t ".category" %>
      </div>
      <div class="col-6">
        <%= select_tag "@categorys",  options_for_select(@categorys.each{|name, id|[ name, id]}), {:class =>"form-select"} %>
      </div>
      <div class="col-4">
        <%= link_to t("layouts.header.search"), home_path, class: "btn btn-secondary", type: "button" %>
      </div>
    </div>
  </div>
</div>
<div class="row mt-2">
  <%= render "home_product" %>
</div>

app/views/products/show.html.erb
<% provide :title, t(".title") %>
<div class="row mt-5 mb-5">
  <div class="col-2 mr-5"></div>
  <div class="col-4 detail_img">
    <%= image_tag @product.image, class: "size_img card-img-top hvr-grow-shadow" %>
  </div>
  <div class="col-4">
    <h2><%= @product.name %></h2>
    <br />
    <div>
      <h5>
        <%= t(".price") %>
        <%= number_to_currency(@product.price) %>
      </h5>
    </div>
    <br />
    <h5><%= t("static_pages.home.category") %>: <%= @product.category_name %></h5>
    <div><%= t(".detail_content") %></div>
    <div class="mt-2">
      <h5><%= t ".size " %></h5>
      <div> <%= t ".size_s_m" %></div>
      <div> <%= t ".size_s" %> <%= Settings.size.size_s %></div>
      <div><%= t ".size_m" %> <%= Settings.size.size_m %></div>
      <div><%= t ".size_l" %> <%= Settings.size.size_l %></div>
      <div><%= t ".size_xl" %> <%= Settings.size.size_xl %></div>
      <div><%= t ".size_xxl" %> <%= Settings.size.size_xxl %></div>
    </div>
    <br />
    <div class="mt-4">
      <%= link_to t("products.home_product.buy"), add_to_carts_path(@product, quantity: 1), class: "btn btn-danger mx-2 mb-2", type: "button" %>
    </div>
  </div>
  <div class="col-2"></div>
</div>