config/routes.rb
Rails.application.routes.draw do
  root "products#home"
  get "/home", to: "products#home"
  get "/introduce", to: "static_pages#introduce"
  get "/register", to: "accounts#new"
  post "/register", to: "accounts#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/show/:id", to: "products#show"
  resources :accounts, except: %i( index destroy )
  resources :oders, only: [:new, :create]
  resources :products
  resources :carts, only: [:index, :create, :destroy] do
    collection do
      get "/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
      get "remove/:id", to: "carts#remove_from_cart", as: "remove_from"
      put "update_cart/:id", to: "carts#update_cart", as: "update"
    end
  end
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer style="background-color: rgb(32, 30, 30); margin-top:20px" class="footer">
    <div class="footer-nav px-5 pt-4">
      <div class="row">
        <div class="col-6 col-lg-2 col-sm-6 col-md-4">
          <h5 class="text-success"><%= t(".overview") %></h5>
          <p class="text-white"><%= t(".introducee") %></p>
        </div>
        <div class="col-6 col-lg-2 col-sm-6 col-md-4">
          <h5 class="text-success"><%= t(".pay") %></h5>
          <p class="text-white"><%= t(".live") %></p>
          <p class="text-white">Online</p>
        </div>
        <div class="col-6 col-lg-2 col-sm-6 col-md-4">
          <h5 class="text-success"><%= t(".address") %></h5>
          <p class="text-white"><%= t(".address_shop") %></p>
        </div>
        <div class="col-6 col-lg-2 col-sm-6 col-md-4">
          <h5 class="text-success"><%= t(".Link") %></h5>
          <p class="text-white">Facebook</p>
          <p class="text-white">Zalo</p>
        </div>
        <div class="col-6 col-lg-2 col-sm-6 col-md-4">
          <h5 class="text-success"><%= t("layouts.footer.customercare") %></h5>
          <p class="text-white">Email: cskh@gmail.vn</p>
        </div>
        <div class="col-6 col-lg-2 col-sm-6 col-md-4">
          <h5 class="text-success">Help</h5>
          <p class="text-white"><%= t("layouts.footer.Contactus") %></p>
        </div>
      </div>
    </div>
    <div class="text-center text-white mt-5">Copyright © 2021 by SHOP.net</div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <b><%= link_to t("shop"), root_path, class: "navbar-brand", style:"font-size:22px" %></b>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
        <ul class="nav navbar-nav ">
          <li class="nav-item mx-2 "><%= link_to t(".home"), home_path, class: "nav-link bi bi-house-fill mp-2" %></li>
          <li class="nav-item mx-2 "><%= link_to t(".car"), carts_path, class: "nav-link" %></li>
          <li class="nav-item mx-2 "><%= link_to t(".contact"), home_path, class: "nav-link" %></li>
          <li class="nav-item mx-2 "><%= link_to t(".introduce"), introduce_path, class: "nav-link" %></li>
        </ul>
        <form class="d-flex" action="/user/search" method="post">
          <input name="keywords" autocomplete="off" value="" class="form-control" type="search" aria-label="Search">
          <%= link_to t(".search"), home_path, class: "btn btn-secondary mx-2", type: "button" %>
        </form>
          <% if logged_in? %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown"  aria-expanded="false">
                <span><i class="bi bi-person-circle"></i></span>  
                <span class="caret"> <%= (session[:account_fullname]) %></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                <li><%= link_to t("accounts.profile"), current_account, class:"dropdown-item" %></li>
                <li><%= link_to t("accounts.change_password"), "#", class:"dropdown-item" %></li>
                <li><%= link_to t("accounts.edits"), edit_account_path(current_account), class:"dropdown-item" %></li>
                <li><%= link_to t("accounts.purchase_history"), "#", class:"dropdown-item" %></li> 
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to t("layouts.header.logout"), logout_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </div>
          <% else %>
            <%= link_to t(".login"), login_path, class: "btn btn-secondary mx-2", type: "button" %>
            <%= link_to t(".register"), register_path, class: "btn btn-secondary mx-2", type: "button" %>
          <% end %>
      </div>
      <ul class="navbar-nav navbar-right">
        <% I18n.available_locales.each do |lang| %>
          <%= link_to lang.to_s.upcase, (request.path+"?locale=#{lang}"), class: "nav-link" %>
          <a class="nav-link"></a>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>